export const ADD_COMPLAINT_REQUEST = 'ADD_COMPLAINT_REQUEST'
export const ADD_COMPLAINT_SUCCESS = 'ADD_COMPLAINT_SUCCESS'
export const ADD_COMPLAINT_FAIL = 'ADD_COMPLAINT_FAIL'

export const ALL_COMPLAINT_REQUEST = "ALL_COMPLAINT_REQUEST";
export const ALL_COMPLAINT_SUCCESS = "ALL_COMPLAINT_SUCCESS";
export const ALL_COMPLAINT_FAIL = "ALL_COMPLAINT_FAIL";

export const COMPLAINT_DCO_APPROVE_REQUEST = "COMPLAINT_DCO_APPROVE_REQUEST";
export const COMPLAINT_DCO_APPROVE_SUCCESS = "COMPLAINT_DCO_APPROVE_SUCCESS";
export const COMPLAINT_DCO_APRROVE_FAIL = "COMPLAINT_DCO_APRROVE_FAIL";

export const COMPLAINT_DCO_REJECT_REQUEST = "COMPLAINT_DCO_REJECT_REQUEST";
export const COMPLAINT_DCO_REJECT_SUCCESS = "COMPLAINT_DCO_REJECT_SUCCESS";
export const COMPLAINT_DCO_REJECT_FAIL = "COMPLAINT_DCO_REJECT_FAIL";